import Head from 'next/head'
import Nav from '../components/Nav';
import Landing from '../components/Landing';
import styles from '../styles/Home.module.css'

const Home: React.FC = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>autumn | code</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Nav />
      <div className={styles.navSpace} /> */}
      <div className={styles.main}>
        <Landing />
      </div>

    </div>
  )
}

export default Home;